<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AirTypePC</AssemblyName>
    <RootNamespace>AirTypePC</RootNamespace>
    <Version>1.0.6</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\airtype.ico</ApplicationIcon>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\logo-pc.png" />
  </ItemGroup>
</Project>
